### ISSUE TITLE
Design a UI to apply frontend filters

### ISSUE THREAD

**Issue by g1y** [iFixit/pulldasher#100]
From the discussion of this RFC: #90

#### Department: 
None

#### Description:

Create a design for a text field to filter the pulls displayed in pulldasher. It is going to be accessed by a hotkey `/` and live updated since everything is client side. Pressing `enter` will save the state of the current search by saving it in the URL bar.

#### Deadline:
None

#### Related Files:
people appreciated the github and waffle editors for tags

**Comment by danielbeardsley** [comment]
I think it should be live-searched (i.e. updated as you type since we have it all client-side). HItting enter could perhaps do a push-state so it maintains it in your url.

**Comment by MooreGuy** [comment]
@danielbeardsley Added that into the description.
