### ISSUE TITLE
Adding Webhooks: Add them automatically when reading the config

### ISSUE THREAD

**Issue by g1y** [iFixit/pulldasher#103]
#### Problem:
It is fairly tedious to add a webhook to point to pulldasher for every single repo that is listed in the config. It is error prone, and also confusing if you've never done it before.

#### Solution:
Having webhooks be automatically added removes the ability for human error when setting up plldasher, and should speed up setup time.

#### To solve this:
Automatically add the webhooks for each repo on startup using the github API for webhooks: https://developer.github.com/v3/repos/hooks/

Allow this functionalitiy to also be called from a command line script so the webhooks can be added while the application is running without restarts.

#### Background:
 We have quite a few repos now. I add a webhook every time I see something not updating in pulldasher. If someone else other than me wants to add a repo, it isn't immediately clear to them that they need to add a webhook for updates in pulldasher to happen, and so we continually have repos that are missing webhooks.

Setting up pulldasher was lengthy and confusing the first time I did it, because the amount of settings in github that need to be configured for it to work. Removing one of those would help a lot for reducing friction in setup.

**Comment by danielbeardsley** [comment]
Totally a good idea. I ended up doing this for [`backhub`](https://github.com/danielbeardsley/backhub/blob/master/bin/register-hooks) and it was good.

I might vote for a CLI tool instead of on-every-restart so that a pulldasher in a crashloop (has happened) doesn't endlessly make more API calls than it already does

**Comment by danielbeardsley** [comment]
We opted instead to just add a Org-wide webhook! Really easy and solves 95% of this problem. Closing.
