### ISSUE TITLE
Research a way to not restart the app when processing a webhook

### ISSUE THREAD

**Issue by MooreGuy** [iFixit/pulldasher#107]
Occassionally processing webhooks fails, this isn't a huge problem since pulldasher will just restart, but since pulldasher runs a ton of api requests on startup, it quickly hits the github api rate limits.

#### Do this:
when processing a github hook, if there is a failure, log it and then carry on serving.

**Comment by danielbeardsley** [comment]
Turns out, we did this already: https://github.com/iFixit/pulldasher/commit/fef91775e263d3210bc814e7708f8ce7971200b3#diff-a2f45ce31f4e6448968731e99d9cc1a7R71
