### ISSUE TITLE
Issue events on pulls: update the pulls table

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/pulldasher#112]
Instead of accidentally creating records in our issues table for pull requests, let's re-introduce the code from #58 (removed in #110)
But make the "update the pull from this GH response" a bit more tolerant of missing fields.

CC @MooreGuy

**Comment by MooreGuy** [comment]
Why add it back in? You didn't explain why?

**Comment by MooreGuy** [comment]
Ah, okay, I see, thanks. Yeah, we talked about a few ways we can make this happen. :+1: for this change

**Comment by danielbeardsley** [comment]
This is still happening:
```
mysql> select count(*) from pulls join issues using (number, repo);
+----------+
| count(*) |
+----------+
|      308 |
+----------+
1 row in set (0.03 sec)
```
