### ISSUE TITLE
Github Checkboxes: Fill in checkboxes automatically

### ISSUE THREAD

**Issue by g1y** [iFixit/pulldasher#113]
Making project plans is super nice because we get to see every step of a project. Making checkboxes makes it easy to see what is done, and what isn't at a glance. Checking off each of these checkboxes to match reality isn't as fun. Every time a checkbox is made, someone has to manually check off each box when pulls get closed.

Wouldn't it be cool to keep track of pulls referenced with a checkbox and fill them in automatically as they get closed?

- [x] Yayer

**Comment by copperwall** [comment]
We could probably do this with https://github.com/probot/probot

**Comment by danielbeardsley** [comment]
I think this is something that should be left outside the project. Pulldasher doesn't write to github's API at all right now and I think that has been somewhat of a project goal.

**Comment by g1y** [comment]
Okay, I wasn't aware it was desired to be read only, but I guess thanks for bringing it up. If we can get a list of issues that reference a specific issue from the API then this could be done with the feature finish script. I'll look and see. If not pulldasher may at least need to store the references in the DB.

**Comment by g1y** [comment]
It appears we can! In issue timelines there is a:
```
referenced
The issue was referenced from a commit message. The `commit_id` attribute is the commit SHA1 of where that happened.```

**Comment by g1y** [comment]
https://developer.github.com/v3/issues/timeline/
