### ISSUE TITLE
:1st_place_medal: Unrecognized emoji

### ISSUE THREAD

**Issue by n-fisher** [iFixit/pulldasher#125]
Problem: 
--
I've experienced pulldasher not accepting un_dev_blocks and cr's due to me using 🥇  (`:1st_place_medal:`). It's of course a low-priority problem, but I think it merits a fix given it is one of the default 5 that show up when you type `:`.

Do this:
--
Make Pulldasher recognize tags with the 🥇  emoji.

**Comment by danielbeardsley** [comment]
I think we've fixed this by updating our regex to be more open.
