### ISSUE TITLE
Add additions/deletions to Pulls and display them

### ISSUE THREAD

**Issue by n-fisher** [iFixit/pulldasher#127]
It would be awesome to see Github's reported Line Additions and Deletions in the PR summary line. This would:
- Let newer devs get into CRs faster as they could find simple pulls to review
- Get smaller changes out quicker as they could get focused in between larger PR reviews
- Be easy to implement as the info is already provided in GitHub's API
![image](https://user-images.githubusercontent.com/1361631/32396722-b11da1d8-c0a3-11e7-9e77-d30a63a0d2c1.png)

Do This
--
1. Modify https://github.com/iFixit/pulldasher/blob/master/migrations/schema.sql with a migration to add additions and deletions to the table. ex:
```sql 
ALTER TABLE `pulls`
ADD COLUMN `additions` int(10) unsigned DEFAULT NULL AFTER `difficulty`,
ADD COLUMN `deletions` int(10) unsigned DEFAULT NULL AFTER `additions` 
```
2. Add Additions and Deletions to Pull DB object: https://github.com/iFixit/pulldasher/blob/03cd266ead69ac698a92d4021da434c085caeb7e/models/db_pull.js#L8-L10
3. Add Additions and Deletions to Pull object functions: https://github.com/iFixit/pulldasher/blob/03cd266ead69ac698a92d4021da434c085caeb7e/models/pull.js#L163-L165 https://github.com/iFixit/pulldasher/blob/03cd266ead69ac698a92d4021da434c085caeb7e/models/pull.js#L204-L206
3. Add additions and deletions here: https://github.com/iFixit/pulldasher/blob/03cd266ead69ac698a92d4021da434c085caeb7e/views/standard/html/pull.html#L6
5. Style the view to have green additions, red deletions in this https://github.com/iFixit/pulldasher/blob/86eee7f02d012362ecba136bf16290c03e0ddded/views/standard/less/components/pull.less#L251

**Comment by kwiens** [comment]
Great idea!
