### ISSUE TITLE
Deploy Instructions: Add icon for visibility

### ISSUE THREAD

**Issue by g1y** [iFixit/pulldasher#128]
Problem:
--
Deploy instructions aren't always visible when nested into the pull description

To solve this:
--
- Make an icon that will catch the eye of those deploying so they know to check for deploy instructions.
- An added bonus would be to have the deploy instructions available when you click on the icon.

Background
--
Some deploys have gone out where the deploy instructions have been missed. Sometimes this isn't bad, sometimes it's really bad.

CC: @addison-grant @evannoronha @djmetzle

**Comment by djmetzle** [comment]
Add it to `feature merge`?

**Comment by evannoronha** [comment]
> Add it to feature merge?

I'd be down with this. It'd be really neat if feature merge could print out deploy instructions for pulls with the corresponding label, but I'd settle for a `Did you read the deploy instructions before merging this pull?` This may be overkill, but including verification beyond tying "yes" may be helpful.
