### ISSUE TITLE
Fastpass: Visibly distinguish fastpass pulls

### ISSUE THREAD

**Issue by saltaverde** [iFixit/pulldasher#133]
## Problem

It's impossible to tell, at a glance, if a pull is a fastpass or not.

## Do This

Differentiate fastpass pulls from all others by a unique color, animation, or some other visual cue.

**Comment by kwiens** [comment]
Honest question: Why do we care?

**Comment by saltaverde** [comment]
To impart a sense of urgency to CR + QA

**Comment by kwiens** [comment]
Why is a fastpass higher priority than milestone issues?

I could see a P0 being higher priority, but a fastpass should just be another part of the milestone. Opinion @davidrans?

**Comment by davidrans** [comment]
Presumably, a fastpass issue is higher priority than the other stuff on your milestone, or has an urgent deadline, so I think it's reasonable to prioritize it higher. Whether putting that info in pulldasher adds unnecessary clutter is another question. I think if we can think of a way to display it that doesn't add too much noise it's a reasonable suggestion.

Maybe weight a pull's sort priority higher if it's `fastpass`?

**Comment by danielbeardsley** [comment]
Or, allow whitelisting of labels to show in the UI
