### ISSUE TITLE
Remove Frozen Pulls UI

### ISSUE THREAD

**Issue by copperwall** [iFixit/pulldasher#136]
We used to have a list of pull requests that were started but stopped due to incomplete specs or other reasons.

We started following a scrum/agile project process and frozen pulls just don't really happen anymore.

## Do This

Remove all aspects of the frozen pull UI.
* Remove documentation from README.md
* Remove less rule from `views/standard/less/components/header.less`
* Remove the `frozen_count` field from the default export in `views/standard/spec/pageIndicators.js`

**Comment by sid2201** [comment]
Hey @copperwall ! I'll take this one.

**Comment by copperwall** [comment]
Okay, go for it!
