### ISSUE TITLE
Move less into webpack build

### ISSUE THREAD

**Issue by copperwall** [iFixit/pulldasher#137]
We're currently using grunt to build less files into a large css file for the application to use. Unfortunately `grunt-contrib-less` uses a library that has a vulnerability and the project hasn't been updated in about a year.

Instead of replacing grunt with gulp or forking the grunt less module, we should get around to moving our less files into webpack.

**Comment by danielbeardsley** [comment]
> should get around to moving our less files into webpack.

What does that mean? Does this mean using webpack as a generic "compiling" pipeline and having it just wrap a cli command? Or something else?

Less compilation can be done in a single CLI command, right? Could we have a grunt task that just runs the less CLI command

**Comment by copperwall** [comment]
Webpack has some loaders that allow you to basically run

`import './public/pulldasher.less` in the entry file of the frontend application and webpack will bundle that less file into the webpack bundle and place the styles in the `head` of the webpage on load.

https://github.com/webpack-contrib/style-loader

**Comment by danielbeardsley** [comment]
Hmm... like it includes the CSS in the JS and the JS creates a style tag and dumps it there?

**Comment by copperwall** [comment]
Yeah, as long as you import/require a less file somewhere in the JS, webpack will use style-loader to add the style file's contents to a `style` tag somewhere in the head.

I've seen a pattern where there's a matching css/less/sass file for each React component, so each component is responsible for "importing" it's own style.

We only have about eight stylesheets so maybe it's not too big of a deal to import those in `public/js/main.js` all at once.

The one weird thing is figuring out how to keep styles working, since I think we change themes by editing the CSS file referenced in a style tag in the header. If we move to webpack, there's no file to change, since all the themes would be in the webpack bundle. I think that `style-loader` lets you explicitly add or remove a file's style by doing something like

```js
import dayTheme from './day_theme.less';
import nightTheme from './night_theme.less';

// Add theme style to page.
if (theme === 'day') {
   dayTheme.use();
} else {
   nightTheme.use();
}
```
