### ISSUE TITLE
Refreshing far too often

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/pulldasher#140]
It seems that pulldasher refreshes the page every few minutes. It doesn't need to do this.

Looking into it, I noticed that when it tries to upgrade to websockets (from long-polling), the socket.io client side ends up firing a 'connect' event. This causes us to send off an authentication request. The server doesn't see our auth token nonce associated with any users (cause the nonce was already used) and sends back 'unauthenticated' after which the client-side promptly reloads itself.

**Comment by copperwall** [comment]
Did this get fixed by #149?

**Comment by danielbeardsley** [comment]
That was the intent! Forgot to link the issue!
