### ISSUE TITLE
Support Signoffs in Pull Request Reviews

### ISSUE THREAD

**Issue by evannoronha** [iFixit/pulldasher#146]
Problem
---
Right now, we can only signoff on a pull by leaving a Pull Request comment.

Feedback left as part of a PR Review doesn't trigger a signoff. This is annoying and leads 
to us pretty avoiding the Reviews feature entirely.

Do This
---
Support signoffs within Pull Request Reviews.

**Comment by djmetzle** [comment]
> This [..] leads to us pretty avoiding the Reviews feature entirely.

That is regrettable. Github reviews are very well thought out. 

![image](https://user-images.githubusercontent.com/6876047/80230326-a8509300-8606-11ea-88d0-300e266c25e8.png)

**Comment by tgines** [comment]
Would love to have this and move more toward using github's own tools. We should be able to pull that status into pulldasher: https://docs.github.com/en/rest/reference/pulls

**Comment by ianrohde** [comment]
I was considering opening an RFC for this, and Seth directed me here. I'm all for this. It's been a bit strange coming from another company that uses Github's built in functionality to a custom workflow. We should have the option to use what we prefer.

**Comment by djmetzle** [comment]
Bump. This is a bug.
