### ISSUE TITLE
Pulldasher:master is currently broken on tooltip dependency

### ISSUE THREAD

**Issue by addison-grant** [iFixit/pulldasher#174]
At least, that's what it seems like. Attempting to deploy master after merging in #173 caused Pulldasher to crash on one thing, and trying to fix that revealed another problem.

First attempt at fix: 2d8af13f5a1b1bde28cc9c695ecfe1c5c66228fe
The second problem that arose was a browser-side error on trying to render tooltips. This manifested in the page failing to load completely. There were some JS errors revealed in the browser console.

This is the only stacktrace I have captured related to the tooltips:

```
Navigated to https://pulldasher.cominor.com/
VM5265 bundle.js:41 Uncaught TypeError: r.hasOwnProperty is not a function
    at u.getOptions (VM5265 bundle.js:41)
    at u.init (VM5265 bundle.js:41)
    at new u (VM5265 bundle.js:41)
    at HTMLDivElement.<anonymous> (VM5265 bundle.js:41)
    at Function.each (VM5265 bundle.js:14)
    at k.fn.init.each (VM5265 bundle.js:14)
    at k.fn.init.t.fn.tooltip (VM5265 bundle.js:41)
    at Object.addTooltip (VM5265 bundle.js:25)
    at VM5265 bundle.js:41
    at Function.y.each.y.forEach (VM5265 bundle.js:25)
```

This is another I saw at one point:

![image](https://user-images.githubusercontent.com/10889879/81239041-88cb4a00-8fb8-11ea-8cd4-cd84b3d2e124.png)

CC @danielbeardsley

**Comment by addison-grant** [comment]
When we figure this out, unfreeze https://github.com/iFixit/pulldasher/pull/181.

**Comment by ardelato** [comment]
@addison-grant where do we stand on this? It has been a while since this issue was created but now it seems that this is impeding #200

**Comment by addison-grant** [comment]
> where do we stand on this?

Not sure. It hasn't been worked on as of now, as far as I know.

**Comment by addison-grant** [comment]
Is there something incorrect about this GH issue? I am seeing `master` deployed currently, I think.
```
agrant@cominor.com ~/pulldasher (master)
$ git show
commit 5b13321e96072aa54a85767817ab22c9831e9038 (HEAD -> master, origin/master, origin/HEAD)
Merge: edfd343 f702edd
Author: Addison Grant <addison-grant@users.noreply.github.com>
Date:   Wed Dec 23 10:25:11 2020 -0800

    Merge pull request #198 from iFixit/add-repo-name-to-card

    Cards: Add repo name
```

```
agrant@cominor.com ~/pulldasher (master)
$ docker ps
CONTAINER ID        IMAGE                                                   COMMAND                  CREATED             STATUS              PORTS                                      NAMES
fe1a31777f14        pulldasher:5b13321                                      "docker-entrypoint.s…"   6 hours ago         Up 6 hours          8080/tcp, 0.0.0.0:8090->8090/tcp           pulldasher
```

**Comment by danielbeardsley** [comment]
I think we reverted the pull that broke master, so ... maybe?

**Comment by addison-grant** [comment]
Oh yes, we did, we reverted the one that updated to 3.5.0, but later merged one that put jquery at 3.5.1. https://github.com/iFixit/pulldasher/pull/181

I'm just confused because I am unsure if this issue has anything to do with https://github.com/iFixit/pulldasher/pull/200

**Comment by addison-grant** [comment]
I guess it just broke in a similar way

**Comment by addison-grant** [comment]
But I think we can close this particular issue.
