### ISSUE TITLE
Serve pages with GH rate-limiting headers

### ISSUE THREAD

**Issue by addison-grant** [iFixit/pulldasher#184]
Pulldasher makes requests on behalf of the logged-in user, right?

Maybe Pulldasher responses to the user should include the github response rate limit headers (described here: https://developer.github.com/v3/#rate-limiting), so pulldasher users know if they're hitting their limit somehow, or are able to debug more easily.

Some of us were getting this message this morning:

![image](https://user-images.githubusercontent.com/10889879/86153293-499c0f80-bab6-11ea-9ed0-183cba59b6da.png)

**Comment by danielbeardsley** [comment]
There's a deeper issue here. Pulldasher knows about the ratelimit and throttles *all* requests to stay under this limit. Perhaps it sometimes doesn't work? Or not all requests are throttled?

I don't think it's helpful to show the info tot he user in the UI cause there's nothing really they can do about it.

**Comment by danielbeardsley** [comment]
Can confirm: every API access is wrapped in the `rateLimit` function: https://github.com/iFixit/pulldasher/blob/master/lib/git-manager.js#L33
