### ISSUE TITLE
Expose Repo Name on Pull Card

### ISSUE THREAD

**Issue by masonmcelvain** [iFixit/pulldasher#197]
Knowing which repo a pull belongs to would reduce confusion and help meetings go a little faster.

### Currently cards look like this:
![image](https://user-images.githubusercontent.com/52104630/102663382-9d1e1a80-4135-11eb-886c-9a146f7dc316.png)

### We want them to look like this:
![image](https://user-images.githubusercontent.com/52104630/102663366-92fc1c00-4135-11eb-852a-8ddb7ba10bf8.png)

## What to do
- Prepend the repository name to the issue number.

If you have opinions about the layout/design, please comment.
- Perhaps we should keep the `#` in front of the issue number?
- Perhaps long repository names should be truncated with `...`?

**Comment by djmetzle** [comment]
This is pretty simple, isn't it?
https://github.com/iFixit/pulldasher/tree/add-repo-name-to-card

https://github.com/iFixit/pulldasher/blob/f81e8b1e0e1af5af47e5aa2035b6751bb949311d/views/standard/html/pull.html#L6

More to it than that?

**Comment by danielbeardsley** [comment]
> This is pretty simple, isn't it?

You're right. It's very easy. We'd probably want to strip off the Org in the interest of brevity.
