### ISSUE TITLE
Don't always show debug indicators

### ISSUE THREAD

**Issue by copperwall** [iFixit/pulldasher#2]
The three debug navbar indicators are currently always displayed. They don't really get in the way, but it'd be nice to only show them when debugging features are explicitly enabled.

@andyg0808 I thought of a few scenarios that could solve this problem, but I'm not sure which would best solve the problem.

### Scenarios

1. One Setting to Rule Them All
 * Set the `config.debug` setting and that determines whether or not the `debugIndicators` are loaded
 * Easy, but doesn't allow dev to start debug mode without restarting pulldasher, or at least reloading the page
 * No way to get only server-side debug logs or client-side debug logs
2. Browser debug can override the server debug setting
 * Maybe user doesn't want to have all of the server-side socket.io logs, but needs to debug some client-side stuff
 * With this scenario, setting `config.debug` will also set client-side debugging, but we could provide ways to enable or disable client-side debugging.
 * A little more flexibility, plus still lets dev start debug instance with full debug capabilities
3. Browser debug is only triggered explicitly
 * With this option, client-side debugging can only be enabled/disabled on the client. Setting `config.debug` will not affect the client-side debugging setting.

**Comment by andyg0808** [comment]
@copperwall: I think 2 is probably the nicest option, and it shouldn't be lots harder than 3. We can probably just conditionally add a little bit of code in the layout.html that starts debug client-side, and have the server only include that if the debug is active.

**Comment by copperwall** [comment]
@andyg0808 I ended up adding the debug setting from `config.js` to the client-side `App` variable. If the setting is false, then `debugIndicators` returns `undefined` in its requirejs definition. This also adds a `debugStart()` function to the `App` variable that sets `App.debug` to `true` when called, and then rerenders the page.

Here's the pull request. #4

**Comment by kwiens** [comment]
Difficulty scope me!

**Comment by andyg0808** [comment]
Fixed in #4.
