### ISSUE TITLE
Sorting: ensure *own* pulls are on top of the dev_blocked column

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/pulldasher#20]
Recent changes to sorting (introduction of milestones perhaps) have made it so that pulls with a milestone show up at the top of the dev_blocked column. They even show up above your _own_ pulls. Which means seeing if there's work that _you_ need to do might require scrolling down.

**Comment by copperwall** [comment]
Sorry, I assumed that having an ordering of

1. Your dev_blocked pulls that are past due
2. Pulls that are past due
3. Your dev_blocked pulls that are on a milestone
4. Pulls that are on a milestone
5. Your pulls that aren't on a milestone
6. Rest by length dev_blocked

would be a good balance.

There's not really a straightforward way to guarantee a pulls is going to show up first or last right now without adding a really big positive or negative score to it.

A quick fix would be to just make preference for the user's pulls higher than the milestone preference could ever be.

**Comment by danielbeardsley** [comment]
Yes, it's hard to say what's right. I'm not a big fan of the current score-based methodology because it's not obvious what the result is going to be. I think I'd be more in favor of an explicit ordering as you've laid out. This can be done by calculating a set of booleans and either bit-shifting them or keeping them in separate fields.

I think my own pulls should always show at the top of dev_block, because I probably won't be doing much with other people's dev_blocked pulls.

**Comment by danielbeardsley** [comment]
This is being replaced with a simpler sorting system in #248
