### ISSUE TITLE
Tooltips get stuck on top left of screen

### ISSUE THREAD

**Issue by bhuminson** [iFixit/pulldasher#206]
Description
--
This only happens on occasion and I haven't found a clear way to repro it consistently but tooltips get stuck on the top left of the viewport.

![image](https://user-images.githubusercontent.com/24502905/114626370-79448e80-9c68-11eb-921d-d070011715dc.png)

**Comment by danielbeardsley** [comment]
The old ui is gone with #278 So this doesn't apply any more.
