### ISSUE TITLE
Send an event on refresh completion

### ISSUE THREAD

**Issue by copperwall** [iFixit/pulldasher#24]
_Migrated from previous repo_

When the backend does a refresh, it should probably send an event when the last data has been sent. This will allow the frontend code to indicate to the user when the data is trustworthy again (by disabling the refresh button until the data has fully updated) and will help avoid spamming of the refresh button. Perhaps the ideal version would be that every client receives a "refresh_begin" event when a refresh starts and a "refresh_finish" event when it ends. These could then allow the system to gently throttle requests, by preventing multiple simultaneous refreshes (there's no reason to do a refresh while another is in progress).

**Comment by kwiens** [comment]
Is this still an issue? @davidrans

**Comment by danielbeardsley** [comment]
It's definitely not clear what's happening and how long it will take when pressing refresh on a pull.

**Comment by copperwall** [comment]
It'd be fun to keep the refresh icon visible and put a rotating CSS animation on it until the refresh completes.

**Comment by danielbeardsley** [comment]
This should be easy to do now that we have a react frontend.

**Comment by danielbeardsley** [comment]
Done with #263 !
