### ISSUE TITLE
signatures: accept unicode emoji

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/pulldasher#26]
[`signatures--accept-unicode-emoji`](https://github.com/iFixit/pulldasher/compare/signatures--accept-unicode-emoji)

**Comment by danielbeardsley** [comment]
Turns out this was a change needed in the config file. Though we should probably change the example one too.

**Comment by kwiens** [comment]
Do you want to open that pull?

**Comment by danielbeardsley** [comment]
Opened.
