### ISSUE TITLE
New frontend: Pulls with no CI are not deploy blocked

### ISSUE THREAD

**Issue by jarstelfox** [iFixit/pulldasher#272]
In the Old UI, a pull with no CI checks would end up in the deploy block column with a notice to deploy carefully. The new UI puts these pulls in the ready column.

**Comment by danielbeardsley** [comment]
Hmm... on second thought, I think I don't want them to be in the blocked column. Does it actually serve a purpose? i.e. do we click "merge" at a different time or do something before or after merging a pull with no CI?

**Comment by erinemay** [comment]
Valkyrie definitely. [Deploying them is more of a process.](https://overlord.ifixit.com/Guide/How+to+Deploy+Valkyrie+Pulls/1078?lang=en)

The purpose I see (for Valkyrie, and maybe other repos) is to alert merge-button-clickers that they might not be able to just press the merge button and expect it to work. 

Although, I suppose some other indication within the pull card would suffice.

**Comment by danielbeardsley** [comment]
> The purpose I see (for Valkyrie, and maybe other repos) is to alert merge-button-clickers that they might not be able to just press the merge button and expect it to work.

Hmm..  Though I just realized that having tests in a commit status doesn't mean that deploy is automated, just that tests are. That said, I bet the correlation is reasonably high that NO tests implies manual deployment.

**Comment by danielbeardsley** [comment]
Don't know why the merged pull didn't close this. It's done.
