### ISSUE TITLE
QA column card order request

### ISSUE THREAD

**Issue by erinemay** [iFixit/pulldasher#280]
Order pulls in the QA column based on the following logic:
1. Full CR first/empty CR last
2. If same CR, order by age of pull (oldest first)
3. `External block` label at the very bottom
4. Currently being tested by others (`QAing` label) to the bottom (just above `external block` pulls)
5. Keep the exception that a user's own `QAing` label on a card will show up at the top of the column
6. Remove any ordering logic around Github milestones

**Comment by danielbeardsley** [comment]
Well defined! Thanks @erinemay !!

**Comment by danielbeardsley** [comment]
I think the sort is better expressed like this:

* QAing (by current user)
* Everything else
  * Not external Block
    * Not QAing
    * QAing
  * External Block
  
Does that make sense?
