### ISSUE TITLE
React UI: Make hover tooltips more usable

### ISSUE THREAD

**Issue by erinemay** [iFixit/pulldasher#284]
### Ideal behavior: 
Hover anywhere in the CR/QA block and get the complete history of CR/QA. 
Hover anywhere on the entire pull card and see the author.
Hover over pull age indicator dots and see the exact age.
![image](https://user-images.githubusercontent.com/72166715/162016438-41a8e26b-0cf1-4f35-b1d1-a9595bcf060e.png)

### Current behavior on the new UI:
Must hover over the specific checkmark to reveal a single CR/QA-er.
No pull author tooltip.
No pull age tooltip. 

(At least as far as I can tell)

**Comment by danielbeardsley** [comment]
The biggest part of this is done: 
![image](https://user-images.githubusercontent.com/26855/173933332-baf84e75-d451-43f0-ae72-bd888e5effd1.png)
