### ISSUE TITLE
No drafts in the QA column, please

### ISSUE THREAD

**Issue by k0rvusk0r4x** [iFixit/pulldasher#294]
As things are with the current Pulldasher, if someone opens a pull and has it marked as a draft, it will end up in the qa column just like any other. This bloats the qa column and takes up time when we go to test it, see it doesn't really have much in the way of info, and then note it is only a draft. It would be really helpful for us if they just didn't show up as long as the "Draft" label is on them. 

Do:
Make pulls labeled "Draft" not show up in the qa column, please.

**Comment by andyg0808** [comment]
This is basically the same as https://github.com/iFixit/pulldasher/issues/230. I'll copy the comment there and close this in favor of it.
