### ISSUE TITLE
Pulls with passing CI appear to be CI blocked

### ISSUE THREAD

**Issue by erinemay** [iFixit/pulldasher#295]
Several pulls with passing CI are acting like they're CI blocked. Refreshing each pull doesn't move them. 
- They appear in the CI column
- They aren't appearing in the QA column

Pulls:
- https://github.com/iFixit/ifixit/pull/42639
- https://github.com/iFixit/ifixit/pull/42635
- https://github.com/iFixit/ifixit/pull/42413
- https://github.com/iFixit/ifixit/pull/42268

![image](https://user-images.githubusercontent.com/72166715/163836692-27bb1ed0-2f8d-4d7c-91eb-83da645a90fa.png)

**Comment by danielbeardsley** [comment]
Turns out, these pulls are missing a "required" CI status "integration". I think the solution here is to have pulldasher show a grey bubble for a required CI that doesn't exist yet.
