### ISSUE TITLE
Only show most recent (QA) stamp

### ISSUE THREAD

**Issue by k0rvusk0r4x** [iFixit/pulldasher#298]
Right now, a separate QA stamp is shown on a pull for each person who has ever QA'd it regardless of whether it is still valid. 

What happens now:

1. Pull gets stamped by tester A.
2. QA stamp box is green. QA stamp is green or blue depending on who is looking.
3. Change made in the code that invalidates the stamp.
4. QA stamp box is no longer green, and the stamp is orange or red depending on who is looking.
5. Pull gets tested and stamped by tester B.
6. The QA stamp box is green. The QA stamp that is orange/red (invalid stamp) remains, and a new QA stamp is added for tester B.
![image](https://user-images.githubusercontent.com/33426643/165358592-7870b286-c67f-47c0-a1de-2639b5bba33b.png)

What should happen:

5. Pull gets tested and stamped by tester B.
6. The QA stamp box is green. The now-invalid stamp is removed and replaced with the new valid stamp that is green/blue.

Note: The number of stamps should reflect the number of required QA's, so if it's a req 2, there should be two.
Second note: I haven't checked if the same thing is happening with CR's, but I image it's likely.

**Comment by danielbeardsley** [comment]
> The now-invalid stamp is removed and replaced with the new valid stamp that is green/blue.

@sterlinghirsh, @masonmcelvain and @evannoronha and I came up with a different but similar spec. I'd like your thoughts:

* Only ever show 1 bubble per *required* signature
   * Signatures beyond the requirements would not be shown except in the hover state as specced below
* If one of those is out of date
   * Show it orange
   * Show it red if you are one of the users that has a previous signature
* On hover:
   * Show all QA / CRs
   * Show their statuses and times
   * Make them link to their respective comments / reviews
   
Thoughts?

**Comment by k0rvusk0r4x** [comment]
> Make them link to their respective comments / reviews

Oooo. I like this. I believe the other aspects will meet our needs and won't hurt anything, so I'm good with it, but it would be good to give other QA team members a chance to chime in.

**Comment by jarstelfox** [comment]
I second this: https://github.com/iFixit/pulldasher/issues/298#issuecomment-1111355565

or is it "third"? Anyways, I vote in favor.

**Comment by andyg0808** [comment]
@danielbeardsley's suggestion above is very similar to what @erinemay was requesting in https://github.com/iFixit/pulldasher/issues/284. Seems like another vote in favor.
