### ISSUE TITLE
"Leaderboard" for stale CR / QA

### ISSUE THREAD

**Issue by adam000** [iFixit/pulldasher#3]
In addition to show the people most eager to CR / QA, it would be a good way to discourage stale CR to display the number of stale CRs / QAs on the board, per person.

Also, this number should probably not include dev_blocked pulls for CR / QA, nor CI blocked pulls for QA.

**Comment by davidrans** [comment]
My stale CRs are the first thing I see when I look at pulldasher, is the purpose of this just to shame repeat offenders?

**Comment by adam000** [comment]
I think some people's workflows don't incorporate Pulldasher, so it would be nice to poke someone and say "hey, you've got 3 stale pulls, would you mind taking a look at them?"

Shaming would also be beneficial... ideally everybody's at 0-1 stale CR / QA, except maybe Monday mornings.

**Comment by kwiens** [comment]
We have a different dashboard for this now.
