### ISSUE TITLE
RFC: Merged pulls: Show recently merged pulls?

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/pulldasher#303]
We recently started keeping merged pulls client-side (see #300). Let's show a list of recently merged pulls (maybe last 10, 20?).

Possibilities:

* Stick them in a chakra Drawer
* Add a checkbox or something in the "Ready" column to show them at the bottom
* Add a new column defaulting to collapsed
* Add a new button that swaps the whole UI with a "closed pulls" view

CC @sterlinghirsh @davidrans @sctice-ifixit

**Comment by davidrans** [comment]
I don't think this is a particularly useful feature for me. Unless it was only pulls that were in the deploy queue, but I don't know how we could figure that out until we're using GitHub's merge queue.

**Comment by danielbeardsley** [comment]
I find myself frequently searching for pulls, not seeing them, then not being sure if they were deployed / closed / or I'm using the wrong search terms. I remember Sterling really being interested in this too. I also look at the deploys / pull-requests channel a *lot* as well.
