### ISSUE TITLE
Bug: Stale CRs not overwritten?

### ISSUE THREAD

**Issue by jarstelfox** [iFixit/pulldasher#317]
![image](https://user-images.githubusercontent.com/857362/168397265-2c7ddef5-bab5-4eef-9d57-d7a61abec0c0.png)

Pull here: https://github.com/iFixit/ifixit/pull/42931

Previously, this would show as only 2 valid CRs, the older out-of-date CR would be dropped.

Concerns:

1) Is the CR count 2 or 3 for this pull?
2) Is this expected UI?

**Comment by danielbeardsley** [comment]
This spec is in flux, but we feel we've got a [good handle on what we want](https://github.com/iFixit/pulldasher/issues/298#issuecomment-1111355565). That issue might be a better place to express ideas on this subject.

**Comment by jarstelfox** [comment]
Closing in favor of https://github.com/iFixit/pulldasher/issues/298
