### ISSUE TITLE
Pulldasher: Support mobile

### ISSUE THREAD

**Issue by jarstelfox** [iFixit/pulldasher#325]
![62E2C93C-0AE7-4CE6-B2FC-15A22D9BF7D7](https://user-images.githubusercontent.com/857362/172978810-17c033fb-dfc8-4d5e-a976-db1f957a1111.png)

😅

**Comment by andyg0808** [comment]
![image](https://user-images.githubusercontent.com/1283490/190237300-21948142-8b6c-4aa6-86b7-34e1e2e056c9.png)
