### ISSUE TITLE
deploy_block PRs whose parent branch is not `master`

### ISSUE THREAD

**Issue by davidrans** [iFixit/pulldasher#338]
I think it'd be nice if we could automatically deploy_block pulls that are dependent on other PRs going out first. One way to identify likely candidates is if their base branch is not `master`.

I know some of our repos use `main` as the master branch, so that might complicate things. Does GitHub's API indicate which is the master branch?

**Comment by jordycosta** [comment]
> I know some of our repos use main as the master branch, so that might complicate things. Does GitHub's API indicate which is the master branch?

Example of a pull request which the parent branch is master
https://github.com/iFixit/ifixit/pull/46808

![Screenshot 2023-03-15 143548](https://user-images.githubusercontent.com/95656772/225449559-4cbd7208-aca5-4fda-991a-998914e1b5e2.jpg)


Example of a pull request which the parent branch is not master
https://github.com/iFixit/ifixit/pull/46899

![base](https://user-images.githubusercontent.com/95656772/225449549-2c5e4e39-458f-47df-9d6a-d446f697fe72.jpg)

https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#get-a-pull-request

**Comment by jordycosta** [comment]
Maybe a quick check that ref is not `master` or `main` could help in determining this

**Comment by davidrans** [comment]
Looks like this API endpoint returns the repo's default branch: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-organization-repositories
