### ISSUE TITLE
Update Pulldasher-Dev title + header

### ISSUE THREAD

**Issue by jordycosta** [iFixit/pulldasher#361]
### Do-this:

![Screenshot 2023-03-17 114214](https://user-images.githubusercontent.com/95656772/225991257-adc86274-1c8f-459d-a9fb-8542b9666401.jpg)

Update the html title and page header whenever someone is on Pulldasher-Dev

This will reduce confusion whenever someone is testing or working with Pulldasher-Dev

**Comment by erinemay** [comment]
Thanks. This was super annoying.
