### ISSUE TITLE
Default draft pulls toggle to off

### ISSUE THREAD

**Issue by erinemay** [iFixit/pulldasher#397]
Pulldasher has the ability to show/hide draft pulls. Right now, it defaults to show. 

1. Set draft pulls default to off.
2. Logged in user should see their own draft pulls even if draft is toggled off.

Context: This came up after a conversation about dev managers checking the dev_blocked column at a glance as well as going through the dev_blocked column to remind and poke at forgotten pulls. Drafts bloated the dev_blocked column, and turning drafts off every time was annoying.

@kwiens suggested auto-closing or auto-cryoing drafts after a certain amount of time. 

@sterlinghirsh 
>I think having a Drafts section below the dev blocked pulls would be reasonably easy to implement and clarify that we don't actually have that many dev blocks.
I'd rather see them separate than hidden by default but I'm not going to die on that hill

@sctice-ifixit 
>I think drafts should be hidden by default, and we should basically ignore them. The point of a draft is to push something to get some feedback before it's done. They're usually shared directly with relevant parties, and if they end up sitting for a while it's likely harmless or will result in an issue also sitting around, which we're already monitoring

**Comment by erinemay** [comment]
Actually, would it make more sense to set this with a cookie like we do with light/dark mode? That way a users preference persists.

**Comment by kthaler** [comment]
After thinking it over, I messaged @danielbeardsley and he recommends using [useBoolUrlState](https://github.com/iFixit/pulldasher/blob/master/frontend/src/use-url-state.ts#L82) to preserve "drafts" in the URL instead of using cookies for user preferences. I agree since it'll stay consistent with the other attributes in the nav bar, but I'm still open to anything.

**Comment by erinemay** [comment]
>he recommends using [useBoolUrlState](https://github.com/iFixit/pulldasher/blob/master/frontend/src/use-url-state.ts#L82) to preserve "drafts" in the URL instead of using cookies for user preferences.

I wanted this to be something that persists, but after thinking about it, this is probably fine as a url param. Persisting the user preference over just defaulting to off with url params benefits those who want to always see all draft pulls. I don't know if anyone cares about enough about that state.

**Comment by danielbeardsley** [comment]
> I wanted this to be something that persists

The intent behind using url params is so you can bookmark your desired views. This also allows you to have multiple tabs open with different views.

**Comment by kthaler** [comment]
I created a pull request: https://github.com/iFixit/pulldasher/pull/399
Let me know if I should change anything.

**Comment by andyg0808** [comment]
@erinemay Re. the rationale: I'm on-board with this now. That makes sense.
