### ISSUE TITLE
Include milestone in sort order

### ISSUE THREAD

**Issue by kwiens** [iFixit/pulldasher#5]
Let's start factoring milestone into the sort order.

Upcoming milestones should be blue, past milestones should be red.

The dev_block date format is 'Jul 19', but we're using the '7/19' format for milestones. Let's make them consistent.

cc @davidrans

**Comment by copperwall** [comment]
@kwiens  I have an implementation for that on the branch [`sort-by-milestone`](https://github.com/iFixit/pulldasher/tree/sort-by-milestone).

In the dev_block, CR, and QA columns, pulls with milestones on them are preferred, and pulls with milestones that are past due are preferred higher.

The milestone label also turns red when the milestone is past due, but it now looks identical to the `deploy_block` label.

I could change the color of the `deploy_block` label, but I also played around with shadows for emphasis on the milestone label.

Where they look the same
![screen shot 2015-10-14 at 6 21 50 pm](https://cloud.githubusercontent.com/assets/2539016/10502382/7c4d2576-72a0-11e5-937a-3ec146d9778f.png)

Don't change the color, but give it a cool shadow
![screen shot 2015-10-14 at 6 16 59 pm](https://cloud.githubusercontent.com/assets/2539016/10502391/86163d04-72a0-11e5-8a04-51738cd4e4ff.png)

Change the color __and__ give it a cool shadow
![screen shot 2015-10-14 at 6 18 47 pm](https://cloud.githubusercontent.com/assets/2539016/10502396/95de8976-72a0-11e5-9ec1-350d4f199a78.png)

We could also change the color of the deploy_block label to be something like orange. Maybe we could change the color of the milestone label from light blue to a darker blue for emphasis.

I'm not really sure.

**Comment by copperwall** [comment]
A less jarring option could include a small orange shadow behind the milestone label

![screen shot 2015-10-15 at 6 36 46 pm](https://cloud.githubusercontent.com/assets/2539016/10531888/31a9c246-736c-11e5-9e0a-2b3986b7d6c6.png)

**Comment by kwiens** [comment]
Let's make them orange. I don't think we need a shadow, and red is probably a bit too aggressive. Orange is used elsewhere on the page where items need attention.

I propose that we change the color of 'QAing', maybe #9775AA

**Comment by tgines** [comment]
`<blink>` tag pls.

I'm not a fan of the shadow. Do we need the red color on the deploy_blocked dates? Maybe we can change the color of the text on the milestone date to red once it's past due.

**Comment by copperwall** [comment]
Alright, I tried red text on the blue background and it was kind of hard to read.

What about this?
<img width="1165" alt="screen shot 2015-10-16 at 11 08 02 am" src="https://cloud.githubusercontent.com/assets/2539016/10549497/4a8eeaae-73f6-11e5-8e5f-dd1ae152cf39.png">

The tooltip could have a "Past Due: <Milestone Name>" as opposed to just "<Milestone Name>"

**Comment by tgines** [comment]
Borders are a bit intense. Try this instead:

![image](https://cloud.githubusercontent.com/assets/705973/10549722/aa22babc-73f7-11e5-8015-eeaea96cdb08.png)

**Comment by copperwall** [comment]
I like that, I'll implement it.
