### ISSUE TITLE
Pulldasher is incorrectly creating 'issues' from Pull Request webhooks

### ISSUE THREAD

**Issue by entendu** [iFixit/pulldasher#57]
[`github-hooks--handle-issue-events-on-pulls`](https://github.com/iFixit/pulldasher/compare/github-hooks--handle-issue-events-on-pulls)

Entries in the `issues` table are being created for pull requests:

`select from_unixtime(date_created), number from issues inner join pulls using(number)`
![image](https://cloud.githubusercontent.com/assets/276273/21598333/e11d5952-d10f-11e6-8334-1cdc45a0f4d5.png)

[This doc](https://developer.github.com/v3/issues/) says we can look for a `pull_request` key to determine if an issue is a pull request.

This breaks chartio queries in unexpected ways, eg showing milestones that are closed as having open issues:

```
SELECT 	i.milestone_title AS 'Milestone', 
		c.`squad`, 
	   ROUND(SUM(i.date_closed > 0) / COUNT(*) * 100) as percent_done_now
FROM coders c
LEFT JOIN metrics.issues i ON (c.github_username = i.assignee) 
WHERE i.milestone_due_on > UNIX_TIMESTAMP() - 24 * 60 * 60 * 90 AND 
	  c.`squad` != 'Other'
GROUP BY c.squad, `Milestone`
ORDER BY MAX(i.milestone_due_on) ASC, c.squad;
 ```
![image](https://cloud.githubusercontent.com/assets/276273/21598344/1eaf0d10-d110-11e6-9f70-4896a56b1333.png)

**Comment by entendu** [comment]
@danielbeardsley and I saw that this is happening when milestones are assigned to pull requests:

```
Jan 02 17:54:41 cominor.com pulldasher[30268]: Tue, 03 Jan 2017 00:54:41 GMT pulldasher:githubHooks Received GitHub webhook, Event: issues
Jan 02 17:54:41 cominor.com pulldasher[30268]: Tue, 03 Jan 2017 00:54:41 GMT pulldasher:githubHooks Webhook action: milestoned for issue #15784
Jan 02 17:54:41 cominor.com pulldasher[30268]: Tue, 03 Jan 2017 00:54:41 GMT pulldasher:db-manager Calling `updateIssue` for issue #15784
```

`updateIssue` is creating the entry in the `issues` table for the pr.

**Comment by danielbeardsley** [comment]
These events started being broadcast in Oct. 2016: https://developer.github.com/changes/2016-10-27-new-label-and-milestone-webhooks/
