### ISSUE TITLE
Repos: Support multiple repos through and through

### ISSUE THREAD

**Issue by danielbeardsley** [iFixit/pulldasher#62]
[`multiple-repos`](https://github.com/iFixit/pulldasher/compare/multiple-repos)

At the moment, pulldasher only supports a single repository. Let's update it to support more than one. We'll still only have one dashboard, but it may have pulls from across multiple repos.

A few record types contain a `repo` column, but nearly all of them will need it (and need it filled in)

**Comment by kwiens** [comment]
💯
