### ISSUE TITLE
Use ES6 Promises

### ISSUE THREAD

**Issue by copperwall** [iFixit/pulldasher#76]
We do a lot of `Promise.denodeify` in our Github library wrapper because the `github` module didn't support Promises at the time. Now it does, so after we update that usage, we won't have a lot of use for `Promise.denodeify` and won't need an extra Promise library.

**Comment by danielbeardsley** [comment]
I think we use other functions provided by that promise library though... like `Promise.all()` and friends.. OH, [That's part of the spec](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/all)

**Comment by copperwall** [comment]
It is! After looking around a little more, it looks like `done()` is non-standard, and we use that a couple places to let errors bubble up.

There's a pretty simple `done` polyfill, but it might not be worth dropping the whole module for. I'll keep playing around with it.

**Comment by copperwall** [comment]
Another alternative is bluebirdjs.com, which is supposed to be a lot less CPU-intensive and memory-intensive than the standard browser promise.

They support `done` as well, but apparently [heavily discourage it](http://bluebirdjs.com/docs/api/done.html).

**Comment by danielbeardsley** [comment]
Unfortunately, they don't mention *why* it's discouraged and the discussion below is useless. :-(

But a polyfill is super-simple:
https://www.promisejs.org/polyfills/promise-done-7.0.4.js
