### ISSUE TITLE
Milestones don't update without manual refresh

### ISSUE THREAD

**Issue by andrewjpiro** [iFixit/pulldasher#84]
I was looking at the pulls and noticed several 'past due' milestones.  This shouldn't happen since we move pulls to the next milestone now. I clicked on all the pulls and found their milestones had been updated but this change wasn't being shown in pulldasher. When I clicked the refresh manually all of them got updated properly.

**Comment by danielbeardsley** [comment]
Just did an experiment.

The actual structure of the notification (for a pull request getting it's milestone modified) is:

```
{
  "action": "demilestoned",
  "issue": {
    "url": "{url of issue}",
    ...
  },
  "pull_request": {
      "url": "https://api.github.com/repos/{user}/{repo}/pulls/19380",
      "html_url": "https://github.com/{user}/{repo}/pull/19380",
      "diff_url": "https://github.com/{user}/{repo}/pull/19380.diff",
      "patch_url": "https://github.com/{user}/{repo}/pull/19380.patch"
   },
...
}
```

Our code assumes that `pull_request` part is a full pull request api object and we 500 when we try to use it for updating a pull. We should instead use the `issue` object or just refresh the pull entirely.
