### ISSUE TITLE
RFC: How should a frontend for filters be done?

### ISSUE THREAD

**Issue by MooreGuy** [iFixit/pulldasher#90]
We have the ability to filter pulldasher right now with URL parameters. There isn't any UI way to make filters other than the cryogenic storage filter which is just a button. It would be really nice to have an easy way to add filters.

What do you all think would be the best way to implement filters in pulldasher?

cc: @iFixit/coders

**Comment by andyg0808** [comment]
Can you expand on what you mean when you say filters? Do you just mean a GUI way to add URL parameters? Or something more than that, like a key-value field pair that is matched?

**Comment by sterlinghirsh** [comment]
I'd like a multi-select of labels pre-populated with all in-view labels, similar to how github's filtering has it. Also, a single-select of milestones. Those are the big ones for me. Maybe an assignee or pull author filter? Maybe a text filter? I think the labels will be the most useful long-term, though.

**Comment by danielbeardsley** [comment]
> I'd like a multi-select of labels pre-populated with all in-view labels, similar to how github's filtering has it

Agreed, though for UI I might suggest a tag-style auto-completer. Or perhaps for an MVP, just an input box that's split on commas, no fanciness (and persisted in a GET param).

**Comment by danielbeardsley** [comment]
> Maybe a text filter?

I think this is even more important to me than any other feature. Just a simple input box that filters the pulls as you type (based on all the text we have for each pull).

**Comment by MooreGuy** [comment]
>Can you expand on what you mean when you say filters? Do you just mean a GUI way to add URL parameters? Or something more than that, like a key-value field pair that is matched?

I am going to leave that completely up to the discussion, my original thoughts were to just have a way to add those url parameters, but I wouldn't want to throw out any good ideas just because it didn't fit that implementation.

**Comment by kwiens** [comment]
I like the idea of filters, but I'm not sure we really need them yet.

If we were going to build something, waffle does a pretty good job:
![image](https://user-images.githubusercontent.com/129007/29226427-e102f394-7e86-11e7-99bf-9d1eab9d36e1.png)

That might be a fun hackathon project.

**Comment by entendu** [comment]
I would be happy if the author filter wasn't case sensitive

**Comment by danielbeardsley** [comment]
I still think a simple input-box text-search activated with a vim-style `/` keypress would be the most amount of gain for the least work.

**Comment by MooreGuy** [comment]
Okay, I'll make an issue for a github style non case sensative input box that can be activated with `/`. It seems like.

>I like the idea of filters, but I'm not sure we really need them yet.

I've seen other squads use them to filter out other squad's pulls. I think they'd be useful but I don't recall anyone saying we need them, it would just be a nice quality of life improvement.
