### ISSUE TITLE
RFC: Use typescript in frontend and backend

### ISSUE THREAD

**Issue by MooreGuy** [iFixit/pulldasher#91]
Typescript is really nice to ensure type safety but also would help with having multiple different objects that are slightly similar but still different. An example of this is where we have a pull that is a model, but also a pull that comes from github.

I think the merits of using typescript are there, I'm not sure how hard it would be to get started using it with pulldasher.

cc: @andyg0808 @copperwall @davidrans @danielbeardsley

**Comment by davidrans** [comment]
I'd rather not make it harder to jump in and work on Pulldasher without a really good reason. I feel like the result of this would be making it more fun, better, safer, etc. for a couple of people to work on it, and more intimidating and time-consuming for anyone else who tried to contribute.

**Comment by andyg0808** [comment]
Flipside: having types would make it clear to newbies what arguments are expected by each function, rather than requiring people just know what to feed each function. Also, it provides a safety net: suppose you're adding a parameter to a method; you don't have to double-check you have all the calls, the code will fail to compile if everything's not updated as it should be.

Disclaimer: I've never used Typescript or Flow; I'm more repeating arguments I've heard.

**Comment by kwiens** [comment]
Sounds like a lot of work for code that's already in a pretty good state.

**Comment by MooreGuy** [comment]
>Flipside: having types would make it clear to newbies what arguments are expected by each function, 

This was exactly how I felt jumping into pulldasher.

**Comment by danielbeardsley** [comment]
I'm not at all familiar with typescript, but from what I recall hearing, it can be a bear to understand / setup / wrap your head around.

I'm not saying I love the way this code is currently organized, but I think typescript isn't a silver bullet. It would be a huge undertaking and would even make it harder for us to maintain (a bunch of people familiar with this code, but unfamiliar with typescript). It would certainly make it easier for those familiar with typescript, but I think it would discourage development overall (from us and others).

That said, I think the goal should be "make it easier to work on" and we should consider all things that push us toward that goal. Fewer overlapping names, consistent data attribute location, a flatter data object, use a strict-object to prevent typos, ... There are lots of small steps to take that would make a big difference.

The division of labor and overall structure is quite good in this project, it's the little things that have made it hard.

**Comment by danielj41** [comment]
> Flipside: having types would make it clear to newbies what arguments are expected by each function, rather than requiring people just know what to feed each function.

I agree, I've had a hard time reviewing PRs in this repo for that reason.

> it can be a bear to understand / setup / wrap your head around.
> ...
> It would be a huge undertaking and would even make it harder for us to maintain

I disagree with this. It's a superset of js, so the only setup (theoretically) would be setting up the compiler.

For the learning curve, I think it's no more difficult than the `php7` type declarations we've already started using.

I'm in favor of using TypeScript.

**Comment by danielbeardsley** [comment]
> I disagree with this. It's a superset of js, so the only setup (theoretically) would be setting up the compiler.

Yes it's a superset, but for those unfamiliar with typescript, I think it'd be a significant hurdle. That is unless we just type the "classes" and not all their members, that would be easy to do and easy to understand, but In that case, I don't think it'd be all that helpful.

I've been reticent to jump into typescript because I've heard that dealing with their type systems or libraries is endless headaches (like the npm eco-system, but much less organized and with poorer tooling). Obviously, I'm *for* typed languages, but "use a typed language" isn't really a plan, it's a wispy goal.

Ok. I just went through the "typescript in 5 minutes" tutorial: https://www.typescriptlang.org/docs/handbook/typescript-in-5-minutes.html

If we're gonna use typescript, we need more spec and more fine-grained tasks than just "use typescript", otherwise this could take a hundred man-hours and be impossible to CR (likely introducing bugs).

**Comment by danielj41** [comment]
> That is unless we just type the "classes" and not all their members, that would be easy to do and easy to understand, but In that case, I don't think it'd be all that helpful.

I think that would be helpful and make the code more readable.

> I've been reticent to jump into typescript because I've heard that dealing with their type systems or libraries is endless headaches (like the npm eco-system, but much less organized and with poorer tooling).

That's a reasonable point. If we use it extensively, I could see us needing to write some type definitions for third-party libraries or github APIs. (Here is an [example of me manually writing type definitions for `redux-undo`](https://github.com/danielj41/audio-pilot/blob/c1b3fc24dd6ab1d29744d6d6f93611d089dd31b1/manual_typings/redux-undo.d.ts)). It may not be worth the effort.

I'd argue that `pulldasher` is a good project to try typescript on. It's disconnected from our main codebase and can be easily reverted if we decide we don't like it.

> If we're gonna use typescript, we need more spec and more fine-grained tasks than just "use typescript"

Sure! I think this is a reasonable plan.

* Get the typescript compiler working, without adding any type annotations to our code.
* Add interfaces for our main object types (e.g., pull request model). These just specify the fields in each object.
* Add type annotations for functions that accept these objects.
* Stop there and re-evaluate whether we like it or not.

**Comment by colebemis** [comment]
I've been doing a lot of reading about TypeScript for my personal projects. I agree that there's an initial cost to switching to TypeScript but from what I've read TS makes a code base more maintainable in the long run. Here are some good resources that I've found:
* [Type Systems Will Make You a Better JavaScript Developer](https://www.youtube.com/watch?v=V1po0BT7kac)
  * His examples are in Flow, but the argument holds true for TypeScript.
* [TypeScript at Slack](https://slack.engineering/typescript-at-slack-a81307fa288d)
  * This documents the process and results of converting an existing JS code base to TypeScript.
* [Migration commit from JS to TS](https://github.com/paulcbetts/spawn-rx/pull/12/files)
  * This is a practical example of how a team ported their JS code to TS.

I vote to try TypeScript.

**Comment by colebemis** [comment]
From the Slack article:
> To us, the benefits of TypeScript dramatically outweigh the downsides — which do exist. Most notable to us is the additional training cost. Developers who have experience using any strongly-typed language usually pick up the syntax within an hour or two, but a file that makes full use of all of TypeScript’s features can look daunting to developers with a vanilla JavaScript background.

>The most obvious solution to that problem is to phase features in slowly — you can simply enable TypeScript without changing any code, add some simple type declarations, and save more complex concepts like inheritance, generics, and advanced types (intersection types, mapped types) for either specific modules or a later stage. In the end, our experience is that one can reap a lot of benefits with the most basic use of TypeScript.

**Comment by MooreGuy** [comment]
Thanks for all the input, I'll make a project plan.

**Comment by kwiens** [comment]
I'm not so sure that we should jump on board with this. It would be interesting, but pulldasher is in a pretty solid place. Additional development will be primarily maintenance.

We're going to get more bang-for-the-buck on our time improving our dev workflow by working on test infrastructure, staging environments, and slack bots than we are rewriting pulldasher. 

I've got no problem using Typescript for new projects.

**Comment by davidrans** [comment]
I agree with Kyle.

If we’re gonna pour time into making pulldasher better code-wise, I’d rather we spend that time learning more about JS best practices, than start playing with some other version of the language.

**Comment by MooreGuy** [comment]
>Additional development will be primarily maintenance.

Yeah, adding type safety can be considered maintenance. It makes the code more maintainable, makes it easier to do the job of further maintenance by preventing more bugs from being introduced by attempts to patch pre-existing bugs.

>We're going to get more bang-for-the-buck on our time improving our dev workflow by working on test infrastructure, staging environments, and slack bots

This is a false dichotomy if you are arguing for not using typescript. There is no reason why all of those would prevent using typescript in pulldasher

>than we are rewriting pulldasher.

That was neither suggested or implied. Cole even posted a great quote from the slack article that blows this assumption out of the water.

>I’d rather we spend that time learning more about JS best practices, than start playing with some other version of the language.

This is also a false dichotomy, you can implement Javascript best practices in Typescript.

**Comment by danielbeardsley** [comment]
> This is a false dichotomy

Heh, I think that term doesn't apply here, the point was about "where to spend time" time is a limited resource, you can't spend it twice :-). A false dichotomy would be "I don't want to rewrite the entire app in Typescript, so we shouldn't do it at all".

> Yeah, adding type safety can be considered maintenance.

True, and it's a trade-off between spending the time making future maintenance easier vs doing that future maintenance.

> That was neither suggested or implied.

True, though we all know how refactoring goes. It's *really* hard to do just a little bit, there is certainly a danger of getting in over our heads.

**Comment by MooreGuy** [comment]
Thanks everyone for their input, I think I have a good grasp of where everyone stands on this.

This won't be prioritized, but would benefit maintainability of the pulldasher project.
