### ISSUE TITLE
CI: Bypass the CI column if there's no integrations for a repo / pull

### ISSUE THREAD

**Issue by kwiens** [iFixit/pulldasher#93]
![image](https://user-images.githubusercontent.com/129007/29223734-7bcb1786-7e7c-11e7-8d34-06371a7994f6.png)

**Comment by copperwall** [comment]
https://github.com/iFixit/pulldasher/blob/master/views/standard/spec/columns.js#L55

The `selector` function for the CI Blocked column is a good place to start.

**Comment by danielbeardsley** [comment]
We can't automatically know if there are any integrations, we just know that CI hasn't run for this pull. The commit status is something that's stored per-commit, and its absence doesn't tell you anything about the future (maybe CI hasn't run, maybe CI will never run, ...)

I'd lean toward making this configurable per-repo in the config: `ci_required: false` or something.

**Comment by copperwall** [comment]
This might be a good reason to have the `repos` list in `config.js` be an object instead of a `org/repo` string.

**Comment by copperwall** [comment]
This was addressed in the short term with https://github.com/iFixit/pulldasher/issues/130 and is probably going to be long term fixed by #102
