### ISSUE TITLE
Replace bower with npm (and webpack?)

### ISSUE THREAD

**Issue by copperwall** [iFixit/pulldasher#97]
Bower tells you not to use it when you install it, so maybe we should listen.

Bower is currently responsible for installing the following front end modules:
* bootstrap
* font-awesome
* requirejs
* requirejs-text
* visionmedia/debug

Our less files expect to be able to import the asset files directly from`bower_components`, so we need to copy the files from `node_modules` to a public directory.

## Bonus

Can we replace requirejs with webpack without changing all of the the `require` and `define` loaders in the front end files?

This blog post might be a good resource for doing that https://medium.com/@andrejsabrickis/bye-bye-bower-or-how-to-migrate-from-bower-to-npm-and-webpack-4eb2e1121a50

**Comment by danielbeardsley** [comment]
There's a pull for this now! #123
