### ISSUE TITLE
Implement the UI for frontend filters

### ISSUE THREAD

**Issue by g1y** [iFixit/pulldasher#98]
From the discussion of this RFC: https://github.com/iFixit/pulldasher/issues/90

#### To close this:

Implement the filter UI for pulldasher. It is going to be accessed by a hotkey `/` and live updated since everything is client side. Pressing `enter` will save the state of the current search by saving it in the URL bar.

The design will be done in here: https://github.com/iFixit/pulldasher/issues/100

#### URL filte parameters:

Pulldasher already has some filter functionality using URL parameters. Here is an example of filtering by asignee: https://pulldasher.cominor.com/?assigned=danielbeardsley,suzukichi,MooreGuy,kimarre,anthonypileggi,djmetzler,soriat,andrewjpiro,selynna,nvaa36

**Comment by MooreGuy** [comment]
Blocked on https://github.com/iFixit/pulldasher/issues/100 being finished.
