### ISSUE TITLE
Add external block icon to pulldasher

### ISSUE THREAD

**Issue by lexahall** [iFixit/pulldasher#99]
In https://github.com/iFixit/pulldasher/issues/87 we decided to add an `external_block` label to pulls that require input or QA from someone outside of our department. I created the `external_block` label:
![image](https://user-images.githubusercontent.com/10774982/29729249-45ac07c2-8990-11e7-88d6-4d2b8d2a8cc9.png) 
But now we need to implement the icon in pulldasher. 

I was thinking we would use a red eye with a slash. Like so:
![image](https://user-images.githubusercontent.com/10774982/29729160-dcfd1a5e-898f-11e7-860f-23dd03c39f47.png)
![image](https://user-images.githubusercontent.com/10774982/29729208-0678518c-8990-11e7-8ab8-4eadb6766339.png)

This mimics the QAing eye that we already have, which is green if someone else is QAing and blue if the viewer is QAing. I made it red with a slash to show that QA (by someone on the QA squad) is currently not possible.

**Comment by entendu** [comment]
is using a label where we landed? I think there was some confusion if the `external_block` "label" meant an actual GH label or if we "label" the pull like we do with `dev_block`.

cc @danielbeardsley @danielj41 @addison-grant

**Comment by danielbeardsley** [comment]
I think we landed on an actual GH label.

**Comment by lexahall** [comment]
I thought that we wanted to use a GH label since the behavior is more in line with adding the `QAing` label (which just adds an icon to the pull), then commenting `dev_block` (which actually moves the pull into a separate column).

**Comment by BaseInfinity** [comment]
Hmm now that I think about it, having it be a text label like Dom mentioned is more in line to our other labels but meh, i dont have strong feelings either way

**Comment by lexahall** [comment]
@BaseInfinity I think it's less in line with our other labels, because it behaves really differently. 
Other text labels like `dev_block` or `deploy_block` move it into a different column. Which we didn't want to do here. 
This behaves almost exactly the same as the QAing label. Which is a standard github label.

**Comment by BaseInfinity** [comment]
Ya I guess it's just weird that pulldasher uses a mix GH labels and text labels, though i like the idea that GH Labels seem to represent a state of the pull. i guess im cool with it as long as we document somewhere in the README since we plan on open sourcing this

**Comment by danielbeardsley** [comment]
> since we plan on open sourcing this
Plan?

![image](https://user-images.githubusercontent.com/26855/29734835-647a481c-89a9-11e7-815f-41d708a59367.png)
![image](https://user-images.githubusercontent.com/26855/29734851-79174a18-89a9-11e7-89a9-a43ca313bb5e.png)

**Comment by BaseInfinity** [comment]
well, we plan on bloggin about it and officially announcing it to ze world

**Comment by MooreGuy** [comment]
I think the github labels are fine for this.

**Comment by kwiens** [comment]
https://medium.com/chris-opperwall/dockerizing-pulldasher-69af687b1a0c
